---
title: "CDT User Guide"
output:
 html_document:
  toc: true
  toc_depth: 1
  toc_float:
   collapsed: false
---

```{r, child = 'cdtcsschunks.Rmd'}
```

<style type="text/css">
div.tocify {
 max-height: 60%;
}
</style>

<div id='toc-index' class='toc-index-class'>

# [CDT GUI](cdt_file_menu.html)

## [Starting CDT](cdt_file_menu.html#cdt.starting)

## [CDT Main Window](cdt_file_menu.html#cdt.main.win)

### [Menu Bar](cdt_file_menu.html#menu.bar)

### [Toolbars](cdt_file_menu.html#toolbars)

### [Open Files](cdt_file_menu.html#open.files)

### [Input and Command Panels](cdt_file_menu.html#cmd.panel)

### [Map and Table View](cdt_file_menu.html#map.view)

### [Output Message](cdt_file_menu.html#out.msg)

### [Status Bar](cdt_file_menu.html#status.bar)

# [CDT Input Data Format](cdt_data_input.html)

## [CDT stations data format](cdt_data_input.html#cdt.format.data)

## [Setting date range](cdt_data_input.html#cdt.date.range)

## [CDT coordinates file](cdt_data_input.html#cdt.coords.data)

## [NetCDF data](cdt_data_input.html#cdt.ncdf.data)

## [NetCDF filename format](cdt_data_input.html#cdt.ncdf.ffrmt)

## [Setting NetCDF data](cdt_data_input.html#cdt.ncdf.setting)

## [CDT dataset format](cdt_data_input.html#cdt.dataset)

# [Format CDT Input Station Data](format_cdt_data.html)

## [Multiple Files](format_cdt_data.html#multiple.files)

## [Single File](format_cdt_data.html#single.file)

# [Manipulating CDT station data format](manipulate_cdt_data.html)

## [Merge two CDT station data format files](manipulate_cdt_data.html#merge.cdtdata)

## [Filtering CDT station data format](manipulate_cdt_data.html#filter.cdtdata)

## [Selecting CDT station data format](manipulate_cdt_data.html#select.cdtdata)

# [Assess Data Availability](assess_availability.html)

# [Download Data](download_data.html)

## [Download Digital Elevation Model](download_data.html#download.dem)

## [Download Country Administrative Boundaries](download_data.html#download.shp)

## [Download Satellite Rainfall Estimates data](download_data.html#download.rfe)

## [Download Reanalysis data](download_data.html#download.reanalysis)

# [Aggregating Time Series](aggregate_TS.html)

# [Aggregate/Disaggregate Spatial NetCDF data](aggregate_SP.html)

# [Transform NetCDF files into CDT Dataset](transform_cdt_dataset.html)

# [Data Extraction](data_extraction.html)

# [Split NetCDF files into CDT NetCDF format](split_netcdf_files.html)

# [Data Format Conversion](data_conversion.html)

## [Conversion to CPT data format](data_conversion.html#conversion.cpt)

## [Converting NetCDF/GeoTIFF/ESRI .hdr Labelled](data_conversion.html#conversion.raster)

## [Create GrADS Descriptor File from CDT NetCDF files](data_conversion.html#conversion.grads)

# [Filling missing dekadal temperature values](fill_na_temp.html)

# [Check Stations Coordinates](check_stations_coords.html)

# [False-Zeros Check for daily rainfall](qc_false_zero.html)

# [Outliers Check for rainfall data](qc_outliers_precip.html)

# [Outliers Check for temperatures data](qc_outliers_temp.html)

# [Homogeneity Test](homogeneity_test.html)

# [Spatial Interpolation](spatial_interpolation.html)

# [Merging Rainfall Data](merging_rainfall.html)

## [Compute Bias Coefficients](merging_rainfall.html#rr.calc.bias)

## [Apply Bias Correction](merging_rainfall.html#rr.apply.bias)

## [Merging Data](merging_rainfall.html#rr.merge.data)

# [Merging Temperature Data](merging_temperature.html)

## [Compute Downscaling Coefficients](merging_temperature.html#tt.calc.downcoef)

## [Reanalysis Downscaling](merging_temperature.html#tt.reanal.down)

## [Compute Bias Coefficients](merging_temperature.html#tt.calc.bias)

## [Apply Bias Correction](merging_temperature.html#tt.apply.bias)

## [Merging Data](merging_temperature.html#tt.merge.data)

# [Scale Merged Data](scale_merged_data.html)

# [Merging - Cross-Validation](cross_validation.html)

## [Precipitation Data](cross_validation.html#rr.cv.mrg)

## [Temperature Data](cross_validation.html#tt.cv.mrg)

# [Spatial Points Data (CDT Format)](validation_cdt_frmt.html)

# [Gridded Data (NetCDF Format)](validation_ncdf_frmt.html)

# [Validate multiple data sets](validation_multi_data.html)

# [Summary Statistics](summary_statistics.html)

# [Derived Climate Variables](derived_climate_variables.html)

# [Climatologies and Anomalies](climatologies_anomalies.html)

# [Spatial Analysis](spatial_analysis.html)

# [Daily Rainfall Analysis](daily_rainfall_analysis.html)

# [Rainy Season Characteristics](rainy_season_characteristics.html)

# [Rainy Season Analysis](rainy_season_analysis.html)

# [Climate Extremes Indices](climate_extremes_indices.html)

# [Drought Indices](drought_indices.html)

# [Plot CDT Station Data](plot_station_data.html)

# [Plot CDT Gridded Dataset](plot_cdt_dataset.html)

# [Plot NetCDF Data (One File)](plot_ncdf_one.html)

# [Plot NetCDF Data (Sequential Files)](plot_ncdf_seq.html)

# [Plot NetCDF Data (Multiple Variables)](plot_ncdf_vars.html)

# [Plot multiple data sets](plot_multiple_dataset.html)

</div>
